### ISSUE TITLE
Add project license

### ISSUE THREAD

**Issue by dlstadther** [gage-russell/pandas-lineage#29]
Need to add opensource license

suggesting Apache 2.0

**Comment by gage-russell** [comment]
I've got "BSD 3-Clause License" slapped into pyproject.toml naively. Appreciate any guidance on the matter!

**Comment by dlstadther** [comment]
The main differences i'm seeing between bsd-3 and apache-2 fall within permission for folks to use the project for patent or trademark use.
https://choosealicense.com/appendix/


In terms of configuration, including it in the `pyproject.toml` only labels the PYPI project with the license. There aren't actually any labeling or material in the github page or files itself. For that, you'll want to add a `LICENSE` file (no extension) with the content of your chosen license.

**Comment by dlstadther** [comment]
I'm happy to submit the PR for this
